#!/bin/bash
#============ LSF Options ============
#QSUB -q gr20101d
#QSUB -ug gr20114
#QSUB -W 24:00
#QSUB -A p=1:t=28:c=28:m=60G

#============ Shel Script ============
set -x

module load intel
module switch intel/15.0.6 intel/16.0.2

ulimit -s unlimited
export OMP_STACKSIZE=10G

aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 5 s 20 < sparse_data10.txt > sd10max-005.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 5 s 20 < sparse_data20.txt > sd20max-005.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 5 s 20 < sparse_data30.txt > sd30max-005.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 10 s 20 < sparse_data10.txt > sd10max-010.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 10 s 20 < sparse_data20.txt > sd20max-010.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 10 s 20 < sparse_data30.txt > sd30max-010.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 20 s 20 < sparse_data10.txt > sd10max-020.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 20 s 20 < sparse_data20.txt > sd20max-020.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 20 s 20 < sparse_data30.txt > sd30max-020.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 30 s 20 < sparse_data10.txt > sd10max-030.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 30 s 20 < sparse_data20.txt > sd20max-030.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 30 s 20 < sparse_data30.txt > sd30max-030.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 100 s 20 < sparse_data10.txt > sd10max-100.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 100 s 20 < sparse_data20.txt > sd20max-100.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 100 s 20 < sparse_data30.txt > sd30max-100.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 200 s 20 < sparse_data10.txt > sd10max-200.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 200 s 20 < sparse_data20.txt > sd20max-200.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 200 s 20 < sparse_data30.txt > sd30max-200.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 300 s 20 < sparse_data10.txt > sd10max-300.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 300 s 20 < sparse_data20.txt > sd20max-300.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 300 s 20 < sparse_data30.txt > sd30max-300.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 10 s 20 < bidiag1000.txt   > bd1000max-10.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 10 s 20 < bidiag10000.txt  > bd10000max-10.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 10 s 20 < bidiag100000.txt > bd100000max-10.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 20 s 20 < bidiag1000.txt   > bd1000max-20.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 20 s 20 < bidiag10000.txt  > bd10000max-20.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 20 s 20 < bidiag100000.txt > bd100000max-20.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 30 s 20 < bidiag1000.txt   > bd1000max-30.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 30 s 20 < bidiag10000.txt  > bd10000max-30.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 30 s 20 < bidiag100000.txt > bd100000max-30.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 100 s 20 < bidiag1000.txt   > bd1000max-100.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 100 s 20 < bidiag10000.txt  > bd10000max-100.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 100 s 20 < bidiag100000.txt > bd100000max-100.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 200 s 20 < bidiag1000.txt   > bd1000max-200.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 200 s 20 < bidiag10000.txt  > bd10000max-200.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 200 s 20 < bidiag100000.txt > bd100000max-200.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 300 s 20 < bidiag1000.txt   > bd1000max-300.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 300 s 20 < bidiag10000.txt  > bd10000max-300.txt
aprun -n $LSB_PROCS -d $LSB_CPUS -N $LSB_PPN numactl -i all ./fileinput_gkl 300 s 20 < bidiag100000.txt > bd100000max-300.txt

