#!/bin/bash
#============ PBS Options ============
#QSUB -q gr20100a
#QSUB -ug gr20114
#QSUB -W 48:00
#QSUB -A p=1:t=68:c=68:m=90G
#============ Shel Script ============
set -x
module load intel
ulimit -s unlimited
export OMP_STACKSIZE=10G
aprun -n $QSUB_PROCS -d $QSUB_THREADS -N $QSUB_PPN ./fileinput_gkl 1 30 s l 100 43933 321961 inputmatrix > 30_1.txt

