SUBROUTINE CGS2(vntemp,V,n,k,j)
  IMPLICIT NONE
  INTEGER n,j,k
  DOUBLE PRECISION  ONE, ZERO, MINUSONE
  PARAMETER ( ONE = 1.0D+0, ZERO=0.0D+0,MINUSONE = -1.0D+0 )
  DOUBLE PRECISION V(n,k),vntemp(n)
  DOUBLE PRECISION,ALLOCATABLE:: tv(:)
  ALLOCATE(tv(j))
  CALL DGEMV('T',n,j,ONE,V,n,vntemp,1,ZERO,tv,1)
  CALL DGEMV('N',n,j,MINUSONE,V,n,tv,1,ONE,vntemp,1)
  CALL DGEMV('T',n,j,ONE,V,n,vntemp,1,ZERO,tv,1)
  CALL DGEMV('N',n,j,MINUSONE,V,n,tv,1,ONE,vntemp,1)
END SUBROUTINE CGS2
